In [5]:
!pip install PyMySQL
!pip install pandas

Requirement already satisfied: PyMySQL in /home/smallweeo/projects/uni/chi/cheminf-EDU/env/lib/python3.12/site-packages (1.1.0)
Collecting pandas
  Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/smallweeo/projects/uni/chi/cheminf-EDU/env/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /home/smallweeo/projects/uni/chi/cheminf-EDU/env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 12.1 MB/s eta 0:00:00m eta 0:00:010:01:01
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 12.2 MB/s eta 0:00:00m eta 0:00:01
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 11.1 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.26.4 pandas-2.2.2 pytz-2024.1 tzdata-2024.1

In [6]:
import pymysql.cursors
import pandas as pd

In [7]:
host = 'den1.mysql6.gear.host'
db = 'situation'
usr = 'situation'
psword = input()

# Connect to the database
connection = pymysql.connect(host=host, user=usr, password=psword, database=db, cursorclass=pymysql.cursors.DictCursor)

In [13]:
# UserId = 'SomeDeviceName'
# sql = "SELECT timestamp, sensorValue FROM lims_timeseries WHERE Fkey_limsDevice = %s"

# with connection.cursor() as cursor:
#   cursor.execute(sql % UserId)

# df_raw = pd.read_sql(sql, connection, params=(UserId,))

sql1 = "SELECT * FROM situation.q17_decarburization_data"

# the pandas mysql is broken for some reason.
# directly use pymysql library api
data = None
with connection.cursor() as cursor:
    cursor.execute(sql1)
    ret = cursor.fetchall()
    data = pd.DataFrame(ret)
data

,id,temperature,oxygen_flow_rate,initial_carbon_content,time,final_carbon_content
0,1,1600.00,300.00,0.040,50.00,0.004
1,2,1650.00,320.00,0.045,60.00,0.003
2,3,1625.00,310.00,0.050,55.00,0.005
3,4,1600.00,300.00,0.042,50.00,0.004
4,5,1590.00,295.00,0.039,45.00,0.003
5,6,1610.00,305.00,0.043,48.00,0.004
6,7,1640.00,315.00,0.046,52.00,0.003
7,8,1630.00,320.00,0.041,56.00,0.004
8,9,1650.00,325.00,0.048,60.00,0.005
9,10,1600.00,300.00,0.040,50.00,0.004
10,11,1580.00,290.00,0.038,44.00,0.003
11,12,1620.00,305.00,0.041,53.00,0.004
12,13,1645.00,320.00,0.047,57.00,0.004
13,14,1635.00,315.00,0.042,54.00,0.003
14,15,1615.00,308.00,0.040,51.00,0.004
15,16,1605.00,300.00,0.039,50.00,0.003
16,17,1595.00,295.00,0.038,45.00,0.003
17,18,1640.00,310.00,0.044,53.00,0.004
18,19,1630.00,305.00,0.042,55.00,0.003
19,20,1610.00,300.00,0.040,50.00,0.004
20,21,1650.00,320.00,0.045,61.00,0.004
21,22,1625.00,310.00,0.041,55.00,0.005
22,23,1600.00,295.00,0.037,48.00,0.003
23,24,1585.00,290.00,0.036,45.00,0.002
24,25,1600.00,305.00,0.039,50.00,0.004
25,26,1620.00,315.00,0.043,52.00,0.003
26,27,1635.00,325.00,0.045,58.00,0.005
27,28,1640.00,320.00,0.044,56.00,0.004
28,29,1650.00,330.00,0.048,62.00,0.004
29,30,1600.00,310.00,0.041,51.00,0.004
30,31,1580.00,290.00,0.035,43.00,0.003
31,32,1590.00,295.00,0.037,47.00,0.002
32,33,1610.00,305.00,0.040,49.00,0.003
33,34,1625.00,310.00,0.042,54.00,0.004
34,35,1630.00,320.00,0.045,55.00,0.004
35,36,1645.00,325.00,0.047,59.00,0.004
36,37,1635.00,315.00,0.043,53.00,0.003
37,38,1620.00,310.00,0.041,52.00,0.004

In [9]:
# df = df_raw[(df_raw['timestamp'] >= '2022-01-14') & (df_raw['timestamp'] <= '2024-02-01')]
# df['timestamp'] = pd.to_datetime(df['timestamp'])
# df = df.set_index('timestamp')
# df = df.resample('10s').first()
# df = df.interpolate()